### ISSUE TITLE
return only named captures when parsing 

### ISSUE THREAD

**Issue by vjeantet** [gemsi/grok#5]
To follow @prep Pull Request #4 :
Add a way to return only named captures when using Parse or MultiParse, to behave a bit more like the original grok tool.

@fxnn proposal : add a new func to keep code readable
```go
grok.ParseOnlyNamedCaptures(string)
```

when parsing a text like
```
127.0.0.1 - - [23/Apr/2014:22:58:32 +0200] "GET /index.php HTTP/1.1" 404 207
```
with 
```
%{COMMONAPACHELOG:mylog}
```

it should return 
```
{
  "mylog": [
    [
      "127.0.0.1 - - [23/Apr/2014:22:58:32 +0200] "GET /index.php HTTP/1.1" 404 207"
    ]
  ],
  "clientip": [
    [
      "127.0.0.1"
    ]
  ],
  "ident": [
    [
      "-"
    ]
  ],
  "auth": [
    [
      "-"
    ]
  ],
  "timestamp": [
    [
      "23/Apr/2014:22:58:32 +0200"
    ]
  ],
  "verb": [
    [
      "GET"
    ]
  ],
  "request": [
    [
      "/index.php"
    ]
  ],
  "httpversion": [
    [
      "1.1"
    ]
  ],
  "rawrequest": [
    [
      null
    ]
  ],
  "response": [
    [
      "404"
    ]
  ],
  "bytes": [
    [
      "207"
    ]
  ]
}
```

**Comment by vjeantet** [comment]
@prep @fxnn Can you give a feedback on this fix, I added the options in the Parse() func.
I did this to follow the original tool way, and it allows a program to parse the way it wants with only one instance of Grok.
Existing Parse func signature is not modified in its usage, options are optionals

**Comment by fxnn** [comment]
Okay, great so far! Now, I'm not yet sure whether the users of your library really want to mix up usages of `NAMEDCAPTURE` and `DEFAULTCAPTURE` with the same Grok instance.

For example, you changed the signature of `AddPattern` so one is able to pass two separate patterns, but I feel that this is rather confusing in most cases. Even your tests always pass the same pattern twice.

**Comment by vjeantet** [comment]
I had a bad feeling about AddPattern
It needs refactoring to only pass one Param, as before.

If someone write a tool like Logstash, it can have only one instance and different way to grok text depending on the input type and user conf.

**Comment by vjeantet** [comment]
We can introduce a default behavior (NamedCapture only or not) during the New().

**Comment by fxnn** [comment]
Are you sure to compare a library like Grok with an application like Logstash? If I needed both behaviours, I could just go ahead and store me two Grok instances; and neither you as author of the library nor the user's memory had to deal with a duplicated pattern cache.

Besides, maybe we could just pass the same options to `AddPattern` that we pass to `Parse`, so everything's simple and consistent.

**Comment by vjeantet** [comment]
I reverted the AddPattern signature to 
```go 
func (g *Grok) AddPattern(name string, pattern string) {}
```

with #6

**Comment by vjeantet** [comment]
grok.New() now accepts options (grok.NAMEDCAPTURE, grok.DEFAULTCAPTURE) to set the default behavior to be used by Parse() or ParseToMulti().

**Comment by prep** [comment]
Sorry for my late reply. Some thoughts looking at the code in master:

1. The options mechanism doesn't allow for adding new option types that require an argument. This might work for now, but it requires a breaking interface change when the time comes (for instance, when you want to supply a preprocessed map of patterns instead of using the default). If it were me, I'd following the crypto/tls package's lead and simply supply the New() function with an Options/Config struct.

2. A minor nitpick, but the norm in Go is to use constants in the form of "DefaultCapture", not "DEFAULTCAPTURE" ;-)

3. Could you explain why both New() and Parse() have an option parameter? As @fxnn said, I cannot really see the use case for mixing both types with 1 Grok object, apart from the test suite of the package itself.

4. @vjeantet Could you tell me what your main goal is with the patterns.go file? If it is speed, then I guess your current implementation does its job, but if it's just so you have the default set of patterns included in the library without having to copy of the patterns directory, then why not simply create a single map of the patterns as-is and then process them when New() is called and you know if the user wants the "default" or the "named" behaviour?

How about something like this?

```go
package grok

// in patterns.go

var patterns = map[string]string{
	"USERNAME":  `[a-zA-Z0-9._-]+`,
	"USER":      `%{USERNAME}`,
	"INT":       `(?:[+-]?(?:[0-9]+))`,
	"BASE10NUM": `([+-]?(?:[0-9]+(?:\.[0-9]+)?)|\.[0-9]+)`,
	"NUMBER":    `(?:%{BASE10NUM})`,
	// etc ...
}

// in grok.go

type Config struct {
	NamedCapturesOnly   bool
	SkipDefaultPatterns bool
	Patterns            map[string]string
}

func New() *Grok {
	return NewWithConfig(&Config{})
}

func NewWithConfig(config *Config) *Grok {
	g := &Grok{config: config, compiledPattern: map[string]*regexp.Regexp{}}

	if !config.SkipDefaultPatterns {
		g.AddPatternsFromMap(patterns)
	}

	return g
}

func (g *Grok) AddPatternsFromMap(m map[string]string) error {
	// sortGraph stuff
	// call denormalizePattern and AddPattern for each item

	return nil
}

func (g *Grok) AddPatternsFromPath(path string) error {
	// ...
	// read the file contents into a map
	// ...

	return g.AddPatternsFromMap(fileContent)
}

func (g *Grok) Parse(pattern string, text string) (map[string]string, error) {
	// ...
	return captures, nil
}

func (g *Grok) ParseToMultiMap(pattern string, text string) (map[string][]string, error) {
	// ... 
	return multiCaptures, nil
}

func (g *Grok) denormalizePattern(pattern string, storedPatterns map[string]string) (string, error) {
	// ...
	for _, values := range r.FindAllStringSubmatch(pattern, -1) {
		// ...

		if g.config.NamedCapturesOnly {
			// ...
		} else {
			// ...
		}
	}
}
```

That way, each Grok object has its own set behaviour, you can add more config/options stuff as the package improves, the Parse*() functions are simple as before and you only have 1 set of builtin patterns, but you can use the patterns in both cases or simply not at all.

**Comment by vjeantet** [comment]
Hello @prep

Thanks for your feedback.

There is so much way to handle configuration during the grok object creation.
For example, Dave Cheney blogged his way to do handle it:
http://dave.cheney.net/2014/10/17/functional-options-for-friendly-apis

So now i’m a bit confused about how to handle configuration while creating the Grok objet  :)

From a technical point of view I really like how Dave handle options, but it needs you to know how the package works internally. :-/

I fully agree with your 1. remark about supplying valued options.

Your 2. remark is right too :) i have to run govet and golint before any commit.

(bullet 3) I did this to let the package’s user to set a default behavior and overwrite it if needed on a call.
You and @fxnn tell that’s not usefull, ***so it should be removed***.


(bullet 4) Your idea is good, but, since yesterday, i use ```go generate``` to build the file ``patterns.go``` from patterns folder, so it’s as simple as using a single map of the patterns folder’s content, and we keep the quick package loading time.
